"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Alliance = { id: string; name: string; slug: string; roleLabel: string; color: string; capacity: number; targetCapacity: number; sortOrder: number; deletedAt: string | null; _count: { currentMembers: number; targetMembers: number; users: number } };
const empty = { name: "", slug: "", roleLabel: "支援盟", color: "#76c2bf", capacity: 100, targetCapacity: 97, sortOrder: 10 };

export function AllianceManager({ initial, regionAdmin }: { initial: Alliance[]; regionAdmin: boolean }) {
  const router = useRouter(); const [rows, setRows] = useState(initial); const [editing, setEditing] = useState<string | null>(null); const [form, setForm] = useState(empty); const [message, setMessage] = useState("");
  function edit(row?: Alliance) { setEditing(row?.id ?? "new"); setForm(row ? { name: row.name, slug: row.slug, roleLabel: row.roleLabel, color: row.color, capacity: row.capacity, targetCapacity: row.targetCapacity, sortOrder: row.sortOrder } : empty); }
  async function submit(event: FormEvent) { event.preventDefault(); const method = editing === "new" ? "POST" : "PATCH"; const url = editing === "new" ? "/api/admin/alliances" : `/api/admin/alliances/${editing}`; const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); if (editing === "new") setRows([...rows, { ...data.alliance, _count: { currentMembers: 0, targetMembers: 0, users: 0 } }]); else setRows(rows.map((row) => row.id === editing ? { ...row, ...data.alliance } : row)); setEditing(null); setMessage(""); router.refresh(); }
  async function remove(row: Alliance) { if (!confirm(`确认停用 ${row.name}？数据可在数据库中恢复。`)) return; const response = await fetch(`/api/admin/alliances/${row.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setRows(rows.filter((item) => item.id !== row.id)); }
  return <><div className="admin-toolbar"><div><h2>同盟列表</h2><p>建议容量限制为95–97，最大容量不超过100。</p></div>{regionAdmin && <button className="primary-action" onClick={() => edit()}>新增同盟</button>}</div>{message && <p className="form-message">{message}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>同盟</th><th>定位</th><th>当前 / 建议</th><th>账户</th><th>容量</th><th>操作</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><i style={{ background: row.color }} /> <b>{row.name}</b><small>{row.slug}</small></td><td>{row.roleLabel}</td><td>{row._count.currentMembers} / {row._count.targetMembers}</td><td>{row._count.users}</td><td>{row.targetCapacity} / {row.capacity}</td><td><button onClick={() => edit(row)}>编辑</button>{regionAdmin && <button className="danger" onClick={() => remove(row)}>停用</button>}</td></tr>)}</tbody></table></div>{editing && <div className="admin-modal"><form onSubmit={submit}><header><h2>{editing === "new" ? "新增同盟" : "编辑同盟"}</h2><button type="button" onClick={() => setEditing(null)}>×</button></header><label>盟名<input value={form.name} disabled={!regionAdmin && editing !== "new"} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Slug<input value={form.slug} disabled={!regionAdmin && editing !== "new"} onChange={(e) => setForm({ ...form, slug: e.target.value })} required /></label><label>定位<input value={form.roleLabel} onChange={(e) => setForm({ ...form, roleLabel: e.target.value })} required /></label><label>颜色<input type="color" value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /></label>{regionAdmin && <><label>最大容量<input type="number" min="97" max="100" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: Number(e.target.value) })} /></label><label>建议容量<input type="number" min="95" max="97" value={form.targetCapacity} onChange={(e) => setForm({ ...form, targetCapacity: Number(e.target.value) })} /></label><label>排序<input type="number" value={form.sortOrder} onChange={(e) => setForm({ ...form, sortOrder: Number(e.target.value) })} /></label></>}<button className="primary-action">保存</button></form></div>}</>;
}
